### ISSUE TITLE
Building pheniqs with bioconda - doesn't like xxd

### ISSUE THREAD

**Issue by jerowe** [biosails/pheniqs#1]
https://github.com/biosails/pheniqs/blob/71303b70a795795108239f0cb0d8afa84b9db19b/Makefile#L91

Is it possible to use hexdump instead?

**Comment by moonwatcher** [comment]
I think so. this just dumps the cli json config into a byte array so I can be part of the compiled binary. Have you tried this? you want to send me a patch?

**Comment by jerowe** [comment]
I'm not terribly familiar with either tool, but I could try it out.

**Comment by moonwatcher** [comment]
hexdump does not have a mode explicitly for this purpose but I can simulate it with a script.
sadly I couldn't just include the one liner in the Makefile since make does horrible things to shell commands...

is hexdump more portable? The script also depends on sed, grep and cat but I can potentially get rid of those dependencies with a little more work. is this a more portable solution?

```sh
#!/usr/bin/env sh

INTERFACE_JSON="interface.json"
CONFIGURATION_H="configuration.h"

echo "size_t interface_json_len = \
$(cat ${INTERFACE_JSON} | \
hexdump -v -e '1/1 "%02x "' | \
wc -w | \
sed 's/ //g');" >> ${CONFIGURATION_H};

echo "const char interface_json[] = {\n    \
$(cat ${INTERFACE_JSON} | \
hexdump -v -e '12/1 "0x%02x, " "\n" "    "' | \
sed -E 's/( 0x  ,)*$//' | \
grep -vE "^\s+$")\n};" >> ${CONFIGURATION_H};
```

**Comment by jerowe** [comment]
I think hexdump is more portable. Let me fire up the bioconda build docker image, and I will get back to you.

**Comment by jerowe** [comment]
Can confirm hexdump is on the condaforge build image. When you replace xxd with hexdump let me know and I will try to build it.

**Comment by moonwatcher** [comment]
ok, try HEAD.

**Comment by moonwatcher** [comment]
is the latest change in the script from echo to printf resolved this? can I close this ticket?

**Comment by jerowe** [comment]
Closing this out in favor of the other ticket.
