### ISSUE TITLE
Install failure with pheniqs-tools (ppkg.py)

### ISSUE THREAD

**Issue by nizardrou** [biosails/pheniqs#13]
Not sure if this is the expected behaviour, but I was running ppkg.py on Dalma (after loading the appropriate build modules) like so,
`./tool/ppkg.py build build/trunk_static.json`

And this is what was printed on the screen,
`DEBUG:Pipeline:loading /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/build/trunk_static.json
DEBUG:Pipeline:creating directory /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static
DEBUG:Pipeline:creating directory /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install
DEBUG:Pipeline:creating directory /home/gencore/.pheniqs/download
DEBUG:Pipeline:creating directory /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/package
DEBUG:Package:fetching https://zlib.net/zlib-1.2.11.tar.gz
INFO:Package:downloaded archive saved zlib 1.2.11 e6d119755acdf9104d7ba236b1242696940ed6dd
INFO:Package:unpacking zlib 1.2.11
INFO:Package:configuring make environment zlib 1.2.11
DEBUG:Package:./configure --prefix=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install
INFO:Package:building with make zlib 1.2.11
DEBUG:Package:make
INFO:Package:installing with make zlib 1.2.11
DEBUG:Package:make install
DEBUG:Package:fetching https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz
INFO:Package:downloaded archive saved bz2 1.0.6 3f89f861209ce81a6bab1fd1998c0ef311712002
INFO:Package:unpacking bz2 1.0.6
INFO:Package:building bz2 1.0.6 dynamic library
DEBUG:Package:make --file Makefile-libbz2_so PREFIX=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install
DEBUG:Package:copying /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/package/bzip2-1.0.6/libbz2.so.1.0.6 to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/lib/libbz2.so.1.0.6
INFO:Package:symlinking libbz2.so.1.0.6 to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/lib/libbz2.so.1.0
INFO:Package:symlinking libbz2.so.1.0.6 to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/lib/libbz2.so.1
INFO:Package:building with make bz2 1.0.6
DEBUG:Package:make PREFIX=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install
INFO:Package:installing with make bz2 1.0.6
DEBUG:Package:make install PREFIX=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install
DEBUG:Package:fetching https://tukaani.org/xz/xz-5.2.4.tar.bz2
INFO:Package:downloaded archive saved xz 5.2.4 50ad451279404fb5206e23c7b1ba9c4aa858c994
INFO:Package:unpacking xz 5.2.4
INFO:Package:configuring make environment xz 5.2.4
DEBUG:Package:./configure --prefix=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install --enable-static
INFO:Package:building with make xz 5.2.4
DEBUG:Package:make
INFO:Package:installing with make xz 5.2.4
DEBUG:Package:make install
DEBUG:Package:fetching https://github.com/ebiggers/libdeflate/archive/v1.0.tar.gz
INFO:Package:downloaded archive saved libdeflate 1.0 17da81b2a058906f087e797fc69399c606a2c011
INFO:Package:unpacking libdeflate 1.0
INFO:Package:building with make libdeflate 1.0
DEBUG:Package:make CC=gcc
DEBUG:Package:copying /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/package/libdeflate-1.0/libdeflate.a to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/lib
DEBUG:Package:copying /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/package/libdeflate-1.0/libdeflate.h to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/include
DEBUG:Package:copying /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/package/libdeflate-1.0/libdeflate.so to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/lib
DEBUG:Package:fetching https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
INFO:Package:downloaded archive saved htslib 1.9 21be5187203df30637dda2e1133cae2e833ef050
INFO:Package:unpacking htslib 1.9
INFO:Package:configuring make environment htslib 1.9
DEBUG:Package:./configure --prefix=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install --disable-libcurl
INFO:Package:building with make htslib 1.9
DEBUG:Package:make
INFO:Package:installing with make htslib 1.9
DEBUG:Package:make install
DEBUG:Package:fetching https://github.com/miloyip/rapidjson/archive/v1.1.0.tar.gz
INFO:Package:downloaded archive saved rapidjson 1.1.0 a3e0d043ad3c2d7638ffefa3beb30a77c71c869f
INFO:Package:unpacking rapidjson 1.1.0
DEBUG:Package:copying rapidjson 1.1.0 header files to /scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install/include
DEBUG:Package:fetching https://codeload.github.com/biosails/pheniqs/zip/HEAD
INFO:Package:downloaded archive saved pheniqs 2.0-trunk None
INFO:Package:unpacking pheniqs 2.0-trunk
INFO:Package:building with make pheniqs 2.0-trunk
DEBUG:Package:make PREFIX=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install with-static=1 PHENIQS_ZLIB_VERSION=1.2.11 PHENIQS_BZIP2_VERSION=1.0.6 PHENIQS_XZ_VERSION=5.2.4 PHENIQS_LIBDEFLATE_VERSION=1.0 PHENIQS_HTSLIB_VERSION=1.9 PHENIQS_RAPIDJSON_VERSION=1.1.0
INFO:Package:installing with make pheniqs 2.0-trunk
DEBUG:Package:make install PREFIX=/scratch/nd48/Pheniqs/pheniqs_latest/pheniqs-master/bin/trunk_static/install`

And here is the error log in the bin folder (bin/trunk_static/error),
`In function ‘mainSort’:
blocksort.c:347:6: warning: inlining failed in call to ‘mainGtU.part.0’: call is unlikely and code size would grow [-Winline]
 Bool mainGtU ( UInt32  i1, 
      ^
cc1: warning: called from here [-Winline]
blocksort.c:347:6: warning: inlining failed in call to ‘mainGtU.part.0’: call is unlikely and code size would grow [-Winline]
 Bool mainGtU ( UInt32  i1, 
      ^
cc1: warning: called from here [-Winline]
blocksort.c:347:6: warning: inlining failed in call to ‘mainGtU.part.0’: call is unlikely and code size would grow [-Winline]
 Bool mainGtU ( UInt32  i1, 
      ^
cc1: warning: called from here [-Winline]
bzip2.c: In function ‘testStream’:
bzip2.c:557:37: warning: variable ‘nread’ set but not used [-Wunused-but-set-variable]
    Int32   bzerr, bzerr_dummy, ret, nread, streamNo, i;
                                     ^
bzip2.c: In function ‘testStream’:
bzip2.c:557:37: warning: variable ‘nread’ set but not used [-Wunused-but-set-variable]
    Int32   bzerr, bzerr_dummy, ret, nread, streamNo, i;
                                     ^
configure: WARNING: GCS support not enabled: requires libcurl support
configure: WARNING: S3 support not enabled: requires libcurl support`

**Comment by nizardrou** [comment]
Ok I think I found where it is installed,

**bin/trunk_static/install/bin/pheniqs**
By looking at the **output** file in the bin/trunk_static/ folder.

So far I tested the help menu and it comes up as expected. I will try running demux next.

I feel a message at the end of the install that shows where the pheniqs command is installed would be helpful.

**Comment by moonwatcher** [comment]
This builds everything under a virtual root. The virtual root is specified in the config. which will be 
bin/trunk_static/install

so the pheniqs executable gets installed in /bin/pheniqs relative to the virtual root.
