### ISSUE TITLE
error while installing pheniqs under centos 6 using ppkg.py

### ISSUE THREAD

**Issue by nizardrou** [biosails/pheniqs#14]
Tried to install pheniqs under centos 6 using the ppkg.py script but it exited with a CRITICAL ERROR,

`./tool/ppkg.py build build/trunk_static.json
DEBUG:Pipeline:loading /home/nd48/pheniqs-master/build/trunk_static.json
DEBUG:Pipeline:creating directory /home/nd48/pheniqs-master/bin/trunk_static
DEBUG:Pipeline:creating directory /home/nd48/pheniqs-master/bin/trunk_static/install
DEBUG:Pipeline:creating directory /home/nd48/pheniqs-master/bin/trunk_static/package
INFO:Package:unpacking zlib 1.2.11
INFO:Package:configuring make environment zlib 1.2.11
DEBUG:Package:./configure --prefix=/home/nd48/pheniqs-master/bin/trunk_static/install
INFO:Package:building with make zlib 1.2.11
DEBUG:Package:make
INFO:Package:installing with make zlib 1.2.11
DEBUG:Package:make install
INFO:Package:unpacking bz2 1.0.6
INFO:Package:building bz2 1.0.6 dynamic library
DEBUG:Package:make --file Makefile-libbz2_so PREFIX=/home/nd48/pheniqs-master/bin/trunk_static/install
DEBUG:Package:copying /home/nd48/pheniqs-master/bin/trunk_static/package/bzip2-1.0.6/libbz2.so.1.0.6 to /home/nd48/pheniqs-master/bin/trunk_static/install/lib/libbz2.so.1.0.6
INFO:Package:symlinking libbz2.so.1.0.6 to /home/nd48/pheniqs-master/bin/trunk_static/install/lib/libbz2.so.1.0
INFO:Package:symlinking libbz2.so.1.0.6 to /home/nd48/pheniqs-master/bin/trunk_static/install/lib/libbz2.so.1
INFO:Package:building with make bz2 1.0.6
DEBUG:Package:make PREFIX=/home/nd48/pheniqs-master/bin/trunk_static/install
INFO:Package:installing with make bz2 1.0.6
DEBUG:Package:make install PREFIX=/home/nd48/pheniqs-master/bin/trunk_static/install
DEBUG:Package:fetching https://tukaani.org/xz/xz-5.2.4.tar.bz2
INFO:Package:downloaded archive saved xz 5.2.4 50ad451279404fb5206e23c7b1ba9c4aa858c994
INFO:Package:unpacking xz 5.2.4
INFO:Package:configuring make environment xz 5.2.4
DEBUG:Package:./configure --prefix=/home/nd48/pheniqs-master/bin/trunk_static/install --enable-static
INFO:Package:building with make xz 5.2.4
DEBUG:Package:make
INFO:Package:installing with make xz 5.2.4
DEBUG:Package:make install
DEBUG:Package:fetching https://github.com/ebiggers/libdeflate/archive/v1.0.tar.gz
INFO:Package:downloaded archive saved libdeflate 1.0 17da81b2a058906f087e797fc69399c606a2c011
INFO:Package:unpacking libdeflate 1.0
INFO:Package:building with make libdeflate 1.0
DEBUG:Package:make CC=gcc
DEBUG:Package:copying /home/nd48/pheniqs-master/bin/trunk_static/package/libdeflate-1.0/libdeflate.a to /home/nd48/pheniqs-master/bin/trunk_static/install/lib
DEBUG:Package:copying /home/nd48/pheniqs-master/bin/trunk_static/package/libdeflate-1.0/libdeflate.h to /home/nd48/pheniqs-master/bin/trunk_static/install/include
DEBUG:Package:copying /home/nd48/pheniqs-master/bin/trunk_static/package/libdeflate-1.0/libdeflate.so to /home/nd48/pheniqs-master/bin/trunk_static/install/lib
DEBUG:Package:fetching https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
INFO:Package:downloaded archive saved htslib 1.9 21be5187203df30637dda2e1133cae2e833ef050
INFO:Package:unpacking htslib 1.9
INFO:Package:configuring make environment htslib 1.9
DEBUG:Package:./configure --prefix=/home/nd48/pheniqs-master/bin/trunk_static/install --disable-libcurl
INFO:Package:building with make htslib 1.9
DEBUG:Package:make
INFO:Package:installing with make htslib 1.9
DEBUG:Package:make install
DEBUG:Package:fetching https://github.com/miloyip/rapidjson/archive/v1.1.0.tar.gz
INFO:Package:downloaded archive saved rapidjson 1.1.0 a3e0d043ad3c2d7638ffefa3beb30a77c71c869f
INFO:Package:unpacking rapidjson 1.1.0
DEBUG:Package:copying rapidjson 1.1.0 header files to /home/nd48/pheniqs-master/bin/trunk_static/install/include
DEBUG:Package:fetching https://codeload.github.com/biosails/pheniqs/zip/HEAD
INFO:Package:downloaded archive saved pheniqs 2.0-trunk None
INFO:Package:unpacking pheniqs 2.0-trunk
INFO:Package:building with make pheniqs 2.0-trunk
DEBUG:Package:make PREFIX=/home/nd48/pheniqs-master/bin/trunk_static/install with-static=1 PHENIQS_ZLIB_VERSION=1.2.11 PHENIQS_BZIP2_VERSION=1.0.6 PHENIQS_XZ_VERSION=5.2.4 PHENIQS_LIBDEFLATE_VERSION=1.0 PHENIQS_HTSLIB_VERSION=1.9 PHENIQS_RAPIDJSON_VERSION=1.1.0
2
version.h generated with PHENIQS_VERSION 2.0.3
configuration.h command line interface configuration generated.
zsh completion _pheniqs generated.
g++ -Wall -Wsign-compare -I/home/nd48/pheniqs-master/bin/trunk_static/install/include -std=c++11 -O3 -c -o json.o json.cpp

cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [json.o] Error 1

CRITICAL:main:make returned 2`

Below is the error log,
`more bin/trunk_static/error 
configure: WARNING: GCS support not enabled: requires libcurl support
configure: WARNING: S3 support not enabled: requires libcurl support`

**Comment by moonwatcher** [comment]
interesting... htslib can build with libcurl but the current setup does not. I can either explicitly ask to build it without or add libcurl to the build. interesting that it only fails on Centos. Where can I run tests on such a Centos server?

**Comment by moonwatcher** [comment]
oh wait, the error log thing about libcurl is just a warning. it failed because the compiler does not recognize "-std=c++11". Pheniqs is written in C++11, it wont compile on old compilers that dont support it, which compiler is this environment setup with?

**Comment by jerowe** [comment]
@nd48, were you on dalma? Did you run  `module load gcc`?

**Comment by twaddlac** [comment]
Not sure what all has been done regarding deploying this, but is this dockerized yet? Shouldn't that take care of most if not all of these issues?

**Comment by moonwatcher** [comment]
As far as I know gcc only fully supports C++11 since 4.8.1

I don’t really see the point of spending time discussing building on compilers prior to that.
