### ISSUE TITLE
--help bug

### ISSUE THREAD

**Issue by dleopold** [biosails/pheniqs#17]
I just updated my pheniqs install and have noticed a strange bug. When i run 
`pheniqs mux --help`
the normal help is displayed. However, if I do it a second time the help does not display and the terminal seems to be stuck in a loop of printing blank lines until I force quit. This continues every subsequent time I try to pull up the help. This first happened to me in gnome-terminal but I get the same behavior using xterm (e.g. it only worked the first time). The bug does not seem to affect the normal functioning of pheniqs (e.g. I can still run a demultiplexing command and it works properly). The bug persisted through multiple uninstall / reinstall attempts. I am not experiencing this behavior with any other command line programs. I installed using miniconda and I am running Linux mint 18.1.

**Comment by moonwatcher** [comment]
Dear Leopold,
Thank you for outlining this bug. It has been fixed and was the last change to make it to 2.0.6. 
I am closing this ticket now but please let me know if you still have any issues.

L.
