### ISSUE TITLE
Citing Pheniqs

### ISSUE THREAD

**Issue by Jachimdejonghe** [biosails/pheniqs#24]
Hello,

Do you have a preferred way of citing Pheniqs? (sorry if I missed it somewhere on the website)

Thanks :)

Jo

**Comment by moonwatcher** [comment]
Hi Jo

We should be submitting a paper in the next few weeks. A pre publication copy will probably be on Biorxiv soon.

I would love to know what you have been doing with it and if there is anything I can help you with.

Lior.

**Comment by moonwatcher** [comment]
Pheniqs 2.0 is on Biorxiv. Should hopefully be published on peer reviewed soon. 
https://www.biorxiv.org/content/10.1101/2021.03.11.434956v1

**Comment by moonwatcher** [comment]
Pheniqs has been published on BMC bioinformatics. https://doi.org/10.1186/s12859-021-04267-5
I am closing the ticket.
