### ISSUE TITLE
Trouble replicating basic behavior

### ISSUE THREAD

**Issue by BenSolomon** [biosails/pheniqs#28]
Hi team. This looks like a really useful tool. Unfortunately, I'm having a hard time replicating even basic behaviors of pheniqs. Hopefully this is just due to my own misunderstanding. But as one of the simplest examples, here is one configuration file I've tried using

```
{
    "input": [
        "I1_mini.fastq.gz",
        "R1_mini.fastq.gz",
        "R2_mini.fastq.gz"
    ],
    "template": {
        "transform": { "token": [ "0::" ] }
    }
}
```

From this very basic test, I would expect to only see reads from `I1_mini.fastq.gz` in the output sam format [(essentially a small adaptations to Example 1.4)](https://biosails.github.io/pheniqs/quickstart) . However, here are the first few lines I get:

```
@HD     VN:1.0  SO:unknown      GO:query
@PG     ID:pheniqs      PN:pheniqs      CL:pheniqs mux --config pheniqs_test_config.json        VN:2.0.4
@RG     ID:undetermined PU:undetermined
A01125:65:HLGNKDRXX:1:1101:1090:1000    77      *       0       0       *       *       0       0       CATGCGAT        FFFFFFFF        FI:i:1  TC:i:3
A01125:65:HLGNKDRXX:1:1101:1090:1000    13      *       0       0       *       *       0       0       CTTAACTTCGGTGTCGGCCCGTAATC      FFFFFFFFFFFFFFFFFFFFFFFFFF      FI:i:2      TC:i:3
A01125:65:HLGNKDRXX:1:1101:1090:1000    141     *       0       0       *       *       0       0       ATGTTTGGGTTCATTTTTCTTTGCATAATCCAGGGAATCATAAATCATGCCAAAGCCAGTTGTCTTGCCACCACCAAAATGAGTTCTGAAT FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF     FI:i:3  TC:i:3
```

As you can see, reads from all 3 input fastq files are present. Can you point out what I am missing?

Thanks!

**Comment by moonwatcher** [comment]
Hi. I suspect you are installing this from Conda. 

I am about to release 2.1 which has API changes so you are following documentations for 2.1 with 2.0.4 API.
What environment are you working on? As a temporary solution until I release 2.1 you can try and build trunk (which is stable) with `bash -c "$(curl -fsSL https://raw.githubusercontent.com/biosails/pheniqs-build-api/master/install_pheniqs.sh)"
`

**Comment by BenSolomon** [comment]
Thanks for the reply! You are indeed correct, I did install from Conda. My `pheniqs` version is 2.0.6. I've actually managed to achieve my specific use case with `UMI_tools` for the time being, but will definitely check out you 2.1 version in the future. Thanks!

**Comment by moonwatcher** [comment]
Pheniqs 2.1.0 is out and updated on Conda.
https://github.com/biosails/pheniqs/releases/tag/2.1.0
