### ISSUE TITLE
Configuration error: leading segment index 1 references non existing input segment

### ISSUE THREAD

**Issue by rspreafico-sgi** [biosails/pheniqs#8]
Getting this error with latest commit (Jul 27 2018) using JSON files from example and test folders.

**Comment by moonwatcher** [comment]
Can you please post your configuration file? Leading segment index is 0 based. So 0 is the first one.

**Comment by moonwatcher** [comment]
Hi 

Sorry, but I did find a  bug that triggered on some cases. Can you please try again:
https://github.com/biosails/pheniqs/commit/11856b0a49b296993c3757c878dfb2bf84b4378e
